# Generated by Django 4.1.7 on 2023-04-13 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analyzer_language', models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('es', 'Spanish')], default='en', max_length=2)),
                ('language', models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('es', 'Spanish')], default='en', max_length=2)),
                ('is_universal', models.BooleanField(default=False)),
                ('is_visible', models.BooleanField(default=True)),
                ('is_private', models.BooleanField(default=False)),
                ('ai_answer', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Analyzer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analyzer_language', models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('es', 'Spanish')], default='en', max_length=2)),
                ('analyzer_type', models.CharField(choices=[('universal', 'Universal'), ('curricular', 'Curricular')], default='universal', max_length=20)),
                ('analyzer_name', models.CharField(max_length=255)),
                ('analyzer_description', models.TextField(blank=True)),
                ('analyzer_visibility', models.CharField(choices=[('visible', 'Visible'), ('hidden', 'Hidden'), ('private', 'Private')], default='visible', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analyzer_access', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Analyzers',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(default='short name', max_length=255)),
                ('question', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionInAnalyzer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_displayed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analyzer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='activity.analyzer')),
                ('question', models.ManyToManyField(blank=True, to='activity.question')),
            ],
            options={
                'verbose_name_plural': 'QuestionInAnalyzers',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.activity')),
                ('analyzer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.analyzer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.question')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='analyzer',
            field=models.ManyToManyField(blank=True, to='activity.analyzer'),
        ),
        migrations.AddField(
            model_name='activity',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
