# Generated by Django 4.1.7 on 2023-05-25 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_activity_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
