# Generated by Django 4.1.7 on 2023-06-20 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_keyusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
