# Generated by Django 4.1.7 on 2023-07-31 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0006_activity_summary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='is_private',
            new_name='private',
        ),
    ]
