# Generated by Django 4.1.7 on 2023-07-17 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0002_creatorquestionlabel_remove_creator_short_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='short_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
