# Generated by Django 4.1.7 on 2023-07-27 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0007_creatorquestion_creator_request_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CreatorContent',
            new_name='CreatorOut',
        ),
    ]
