# Generated by Django 4.1.7 on 2023-07-27 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0008_rename_creatorcontent_creatorout'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CreatorOut',
            new_name='CreatorOutput',
        ),
    ]
