# Generated by Django 4.1.7 on 2023-07-27 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0009_rename_creatorout_creatoroutput'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CreatorQuestion',
            new_name='ConsolidatedQuestions',
        ),
    ]
