# Generated by Django 4.1.7 on 2023-07-27 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0010_rename_creatorquestion_consolidatedquestions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionLabal',
            new_name='CreatorQuestion',
        ),
    ]
