# Generated by Django 4.1.7 on 2023-07-27 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0011_rename_questionlabal_creatorquestion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionLabelGroup',
            new_name='CreatorQuestionGrouping',
        ),
    ]
