# Generated by Django 4.2.2 on 2023-10-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0015_alter_creatorrequest_short_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consolidatedquestions',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='consolidatedquestions',
            name='creator_question_label',
        ),
        migrations.AddField(
            model_name='creatorquestion',
            name='creator_question_category',
            field=models.CharField(choices=[('analyze', 'Analyze'), ('compose', 'Compose'), ('analyze_compose', 'Analyze and Compose')], default='analyze', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='creatorquestion',
            name='creator_question_type',
            field=models.CharField(choices=[('output', 'Output'), ('global', 'Global'), ('detail', 'Detail'), ('transversal', 'Transversal'), ('specific', 'Specific'), ('item', 'Item')], default='output', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='creatorquestion',
            name='help_text',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='creatorquestion',
            name='internal_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='creatorquestion',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('es', 'Spanish')], default='en', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='creatorquestion',
            name='user_input',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='creatorquestion',
            name='variable_type',
            field=models.CharField(choices=[('free_text', 'Free Text'), ('single_select', 'Single Select'), ('multi_select', 'Multi Select'), ('numerical_increment', 'Numerical Increment'), ('tag_multiselect', 'Tag Multiselect')], default='free_text', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='creatorquestion',
            name='question_label',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='Creator',
        ),
        migrations.DeleteModel(
            name='CreatorQuestionLabel',
        ),
        migrations.DeleteModel(
            name='Desired',
        ),
    ]
